#!/usr/bin/env ruby

require_relative './helper'
require 'yaml'
require 'fileutils'
require 'mongo'

ROOT_FOLDER = "./standalone"
maker = MongoEnvMaker.new(ROOT_FOLDER)

puts "Creating 2 standalone dbs: localhost:27018 & localhost:27019"
puts "create the directories"

maker.spawn(27018)
maker.spawn(27019)

puts ">> pids: #{maker.pids}"

File.open( File.expand_path("./#{ROOT_FOLDER}/.processes"), 'w' ) do |out|
  YAML.dump( maker.pids, out )
end

sleep 2

puts "Seed 27018 with some data..."
DummyData.seed("localhost", 27018)

