#!/usr/bin/env ruby

require 'yaml'
require 'fileutils'

puts "killing the 2 standalone dbs"

full_path = File.expand_path("./standalone/.processes")

if File.exist?(full_path) && YAML.load(File.open(full_path))
  pids = YAML.load(File.open(full_path))
  puts "found pids: #{pids}"
  pids.each{ |pid| `kill -9 #{pid}` }
  FileUtils.rm full_path
else
  puts "couldn't find path"
end
